# SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and Project Persephone contributors
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ConfigMap
metadata:
  name: persephone-sync-policy
  namespace: garden
data:
  syncConfig: |
    data-types-to-sync:
      - projects
    namespace-format: "%i"
