# SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and Project Persephone contributors
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: persephone-webhook
  namespace: garden
  labels:
    app: persephone
    role: webhook
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: persephone
      role: webhook
