# SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and Project Persephone contributors
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Secret
metadata:
  name: authentication-webhook-config
  namespace: garden
stringData:
  kubeconfig: |
    apiVersion: v1
    kind: Config
    preferences: {}
    clusters:
      - cluster:
          insecure-skip-tls-verify: true
          server: https://persephone-webhook:9443/validate-authentication-k8s-io-v1-tokenreview
        name: webhook
    users:
      - name: webhook
    contexts:
      - context:
          cluster: webhook
          user: webhook
        name: webhook
    current-context: webhook

---

apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: persephone-webhook-token
  namespace: garden
  labels:
    resources.gardener.cloud/purpose: token-requestor
    resources.gardener.cloud/class: shoot
  annotations:
    serviceaccount.resources.gardener.cloud/name: persephone-webhook
    serviceaccount.resources.gardener.cloud/namespace: garden
    serviceaccount.resources.gardener.cloud/inject-ca-bundle: "true"

---

apiVersion: v1
kind: Secret
metadata:
  name: persephone-managedresource-rbac-webhook
  namespace: garden
type: Opaque
stringData:
  clusterrole.yaml: |
    apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    metadata:
      name: persephone-webhook
      labels:
        app: persephone
        role: webhook
    rules:
    - apiGroups:
      - admissionregistration.k8s.io
      resources:
      - mutatingwebhookconfigurations
      verbs:
      - get
      - list
      - watch
      - create
    - apiGroups:
      - admissionregistration.k8s.io
      resources:
      - mutatingwebhookconfigurations
      resourceNames:
      - persephone-webhook
      verbs:
      - patch
      - update

    - apiGroups: [""]
      resources:
      - namespaces
      - secrets
      - resourcequotas
      verbs:
      - "*"
    - apiGroups:
      - core.gardener.cloud
      resources:
      - internalsecrets
      verbs:
      - "*"
    - apiGroups:
      - rbac.authorization.k8s.io
      resources:
      - roles
      - rolebindings
      verbs:
      - "*"
    - apiGroups:
      - core.gardener.cloud
      resources:
      - projects
      verbs:
      - create
      - list
      - get
      - watch
    - apiGroups:
      - core.gardener.cloud
      resources:
      - shoots/adminkubeconfig
      verbs:
      - create
    - apiGroups:
      - security.gardener.cloud
      resources:
      - credentialsbindings
      verbs:
      - "*"

  clusterrolebinding.yaml: |
    apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    metadata:
      name: persephone-webhook
      labels:
        app: persephone
        role: webhook
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: persephone-webhook
    subjects:
    - kind: ServiceAccount
      name: persephone-webhook
      namespace: garden
